### PR TITLE
add issue template

### PR DESCRIPTION
**Pull request by VladimirAlexiev**

### CODE REVIEW

**Comment by cygri** [comment]
I would suggest a few more sections, maybe along the lines of this:
https://www.python.org/dev/peps/pep-0012/#suggested-sections

“Open Issues” and “Rejected ideas” seem particularly important if we assume that the issues will be refined over time based on the discussion. “Security implications” seems good to have!

**Comment by afs** [comment]
A simple template is a good idea - I suggest keeping it simple for the initial issue and refine it as part of discussion. The goal is more detail in a template for write-up for the output report.

**Comment by JervenBolleman** [comment]
Is the issue template added as in #11 ok? If so I can close this pull without merging?

**Comment by rubensworks** [comment]
@JervenBolleman I proposed some improvements to the template in #50.

**Comment by JervenBolleman** [comment]
I think this has been superseded by #50  and #11 and am going to close without merging.
If you are unhappy about that please speak up and I will undo it.

**Pull request closed without merging**
