### PR TITLE
SEP-0002 Updates

### LINKED ISSUE #109: SEP2: We should extend ADJUST() to work with argument types of xs:date and xs:time.
**Idea to improve SEP 2**

We should extend `ADJUST()` to work with argument types of xs:date and xs:time as well.

Adjust functions are described [here](https://www.w3.org/XML/Group/qtspecs/specifications/xpath-functions-31/html/Overview.html#timezone.functions)

### LINKED ISSUE #110: SEP2: Add the operator: xs:time + xs:dayTimeDuration
**Idea to improve SEP 02**

We are missing the following operator: xs:time + xs:dayTimeDuration

### PR DESCRIPTION
**Pull request by kasei**
Fixes #109.
Fixes #110.

### CODE REVIEW

**Comment by JervenBolleman** [comment]
I need to check why there are merge conflicts but otherwise looks good. Will merge on wednesday when I have the time to do a proper look. Or andy beats me to it.

**Comment by kasei** [comment]
Ah, sorry about that. There was some weirdness about it not recognizing the previous PR, I think. It had a lot commits listed, even though only one or two of them represented the actual changes. I can try to start a fresh branch and submit a new PR if you want...

**Comment by kasei** [comment]
@JervenBolleman did you want me to try a fresh PR, or can this be merged?

**Comment by JervenBolleman** [comment]
I cherry-picked the two newest commits, as I couldn't get a nice rebase working.

**Pull request closed without merging**
