### PR TITLE
Replace a lot of HTML with Markdown in 007

### PR DESCRIPTION
**Pull request by JervenBolleman**
Also add sparql syntax highlighting.

### CODE REVIEW

**Comment by JervenBolleman** [comment]
@afs I hope I did not make a mess of your nice work.

**Comment by afs** [comment]
Thanks - I'll take a look ASAP. 

If this becomes real, it's back to HTML for W3C ReSpec HTML format.

We may wish to factor that in going forwards.

**Review by afs — APPROVED** [review]
Looks good!

**Comment by JervenBolleman** [comment]
@afs will you hit the rebase and merge button, or do you want me to do it?

**Comment by afs** [comment]
@JervenBolleman - I've put this commit and the improvements from #171 in as PR #172.

If/when that is merged, then I'll come back and tidy anything GH does not automatically sort out.

**Pull request closed without merging**
