### PR TITLE
Adds XPath operators 2.0 links to SEP 2

### PR DESCRIPTION
**Pull request by Tpt**
Allows to easily go to the XPath function specifications from the SEP 2 text

### CODE REVIEW

**Comment by JervenBolleman** [comment]
@Tpt can you link your w3c account to [github](https://www.w3.org/users/myprofile/connectedaccounts)? Makes the contribution rights tracking easier.

**Comment by namedgraph** [comment]
Latest XPath F&O spec is 3.1 though? https://www.w3.org/TR/xpath-functions/

**Comment by Tpt** [comment]
@JervenBolleman Sure, it's now done.

@namedgraph I linked to XPath F&O 2 because the SEP states "For the purposes of this SEP, it is assumed that XPath 3.1 is *not* supported, and existing SPARQL semantics continue to be based on [XQuery 1.0 and XPath 2.0 Functions and Operators](https://www.w3.org/TR/xpath-functions/).". Updating the links to XPath F&O 3 should be a simple find/replace. It's especially meaningful here because of the "timezone vs no timezone" behavior that is not the same between XPath F&O 2 and XPath F&O 3.

**Review by JervenBolleman — APPROVED** [review]

**Comment by afs** [comment]
SPARQL can't remain on F&O v2 forever. We might as well link to v3.1.

**Comment by Tpt** [comment]
@afs @ericprud @JervenBolleman I have updated the links to target the latest F&O specification.

**Review by kasei — APPROVED** [review]

**Review by ericprud — APPROVED** [review]
nice to have links on everything

**Pull request merged**
