### PR TITLE
SEP-0006 for Lateral Join. SEP-0007 for variable substitution

### PR DESCRIPTION
**Pull request by afs**
Contributing material to the SPARQL 1.2 CG.

### CODE REVIEW

**Review by JervenBolleman — APPROVED** [review]
@afs thank you, very much for this kind work! It is wonderful in its detail.

**Comment by TallTed** [comment]
This was merged MUCH too quickly (created 11:31am ET Saturday, merged 3:33am ET Monday)!  Producing the PR which is needed (fixing some punctuation, among other things) will take much longer than some change suggestions on this PR would have.  I strongly urge that PRs be left open for *at least* one business day, preferable more, to allow for review by other involved parties.

**Comment by Jamie-SA** [comment]
Probably should reference the issues related to this PR. For instance: #100

**Comment by JervenBolleman** [comment]
@TallTed I agree, we should find some middle ground between 2 years and 2 days ;) for merging pull requests. Making a pull request for punctuation etc. should not take that long. 

@Jamie-SA could you be so kind as to edit the SEPs to add it?

**Comment by TallTed** [comment]
@JervenBolleman — As I said, "_fixing some punctuation, **among other things**_" — i.e., there's more than punctuation to be addressed. (@afs — tagging you because the question below goes to you)

The first is a broken sentence in [lines 25–28 of SEP-0007](https://github.com/w3c/sparql-12/blob/main/SEP/SEP-0007/sep-0007.md?plain=1), which meaning I cannot discern, and PRs are not built for asking the original author what they meant by something like "_evaluates a graph pattern where there is a **specific are variables** given by a solution mapping._"

There are likely to be more of this kind of thing.  This is why reviewing, making suggestions, and asking questions on a PR is better, easier, and faster than creating a PR to revise the other PR.

**Comment by afs** [comment]
I've opened discussions:

https://github.com/w3c/sparql-12/discussions/168
and
https://github.com/w3c/sparql-12/discussions/169

**Comment by afs** [comment]
@TallTed, Fixed the text. Could you separate directed comments please?

**Comment by TallTed** [comment]
@JervenBolleman — I am well aware of how to produce a PR, or in this case, 2, as it is easier and faster to focus on one document at a time; and I do have browser tabs open for this task, but the SPARQL 1.2 work hasn't been chartered to a WG yet, so it's relatively lower priority than multiple other tasks and groups on my plate. 

If you would use GitHub's web UI to walk through the task of closely reading someone else's PR and making change suggestions and flagging unclear text points, etc., and compare that to the task of editing a merged document in similar way (that is, noting and applying change suggestions directly), while flagging unclear text (which is typically the basis for an Issue, not a PR, because PRs don't have tools for highlighting problematic text and commenting thereon; only for *changing* that text, which is not always possible, as in this case), you may notice that the latter is *substantially* more effortful.

If not so for you, that's wonderful; you may proceed with that route as you like. It *is* so for me, and I believe for the vast majority of GitHub users who work through the GitHub web UI, and this is why I ask that PRs be left open for *at least* one, if not a few, working days before they get merged, so that the faster and easier corrective approach of change-requests may be used.

**Comment by TallTed** [comment]
> [@afs] Fixed the text. Could you separate directed comments please?

Thank you for fixing the text. I am not sure what you mean by "separate directed comments"... If you mean, use one comment for each tagged person, I generally do so. In this case, it seemed reasonable to address two in one, as the issues were connected. I'll try to remember not to combine such in future when you're involved.

**Pull request merged**
